/**
 * Azure OpenAI helper for Vercel Serverless Functions
 */

export async function callAzureOpenAI({ messages, stream = false, model }) {
    const url = process.env.AZURE_OPENAI_ENDPOINT;
    const apiKey = process.env.AZURE_OPENAI_API_KEY;
    const selectedModel = model || process.env.AZURE_OPENAI_MODEL || 'gpt-4.1';

    if (!url || !apiKey) {
        throw new Error('Missing AZURE_OPENAI_ENDPOINT or AZURE_OPENAI_API_KEY in environment variables');
    }

    const input = messages.map(m => ({
        type: 'message',
        role: m.role,
        content: m.content
    }));

    const body = {
        model: selectedModel,
        input: input,
        stream: !!stream
    };

    const res = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'api-key': apiKey
        },
        body: JSON.stringify(body)
    });

    if (!res.ok) {
        const txt = await res.text();
        throw new Error(`Azure API error: ${res.status} - ${txt}`);
    }

    return res;
}

export function sanitizeContent(raw, maxLen = 4000) {
    if (!raw) return '';
    let s = String(raw);
    s = s.replace(/data:[^\s"'>]+;base64,[A-Za-z0-9+/=]+/g, ' [removed embedded data] ');
    s = s.replace(/!\[[^\]]*\]\([^\)]*data:[^\)]+\)/g, ' [removed image] ');
    s = s.replace(/<\/?[^>]+>/g, ' ');
    s = s.replace(/&nbsp;|&lt;|&gt;|&amp;|&quot;|&#\d+;/g, ' ');
    s = s.replace(/\s+/g, ' ').trim();
    if (s.length > maxLen) {
        s = s.slice(0, maxLen) + ' [truncated]';
    }
    return s;
}

export async function generateSessionTitle(promptContent) {
    try {
        if (!promptContent || typeof promptContent !== 'string') return null;
        const cleanPrompt = sanitizeContent(promptContent, 500);
        if (!cleanPrompt) return null;

        const res = await callAzureOpenAI({
            messages: [
                {
                    role: 'system',
                    content: 'You are a helpful assistant. Generate a short, concise, and appropriate title (3 to 5 words maximum) for a chat session based on the user\'s message. Return ONLY the plain text title without quotes, trailing punctuation, or markdown formatting.'
                },
                { role: 'user', content: cleanPrompt }
            ],
            stream: false
        });

        const json = await res.json();
        let text = '';
        if (json.choices && json.choices[0] && json.choices[0].message) {
            text = json.choices[0].message.content || '';
        } else if (json.output && json.output[0] && json.output[0].content && json.output[0].content[0]) {
            text = json.output[0].content[0].text || '';
        }

        let title = text.trim().replace(/^["'«»“”`]+|["'«»“”`]+$/g, '').replace(/^Title:\s*/i, '').replace(/\.$/, '').trim();
        if (title.length > 50) {
            title = title.slice(0, 50).trim() + '...';
        }
        return title || null;
    } catch (err) {
        console.error('Error generating session title:', err);
        return null;
    }
}

export async function assessScaleLevel(userMessageContent) {
    try {
        const cleaned = sanitizeContent(userMessageContent, 2000);
        if (!cleaned) return [1];

        // Immediate heuristic for full generative requests
        const gen5Pattern = /(create|write|generate|compose|draft|produce|make|build)[^\n]{0,60}\b(essay|paragraph|report|article|poem|story|code|program|script|presentation|slide\s*deck|slides)\b/i;
        if (gen5Pattern.test(cleaned)) {
            return [5];
        }

        const res = await callAzureOpenAI({
            messages: [
                {
                    role: 'system',
                    content: `Assess the User input according to the following scale: \n
1. No AI: This represents tasks or processes that are done entirely by humans without any AI involvement.\n
2. Ideas and Structure: This level indicates that AI is used to generate ideas or structure content, but the primary content creation is still human-driven.\n
3. AI Editing: At this stage, AI is used to assist with editing or refining content that has been primarily generated by a human.\n
4. AI + Human Evaluation: Here, both AI and humans are involved in creating and evaluating the content. This stage likely involves a collaborative effort where AI generates content or makes suggestions, and humans refine or approve it. This does not include examples where AI generates most of the content.\n
5. Full AI: AI is almost fully responsible for the task or process with little to no human intervention. For example: create me a essay about ... or create me a paragraph about... \n
Please return only the number and category (e.g., '5. Full AI') that the user's messages correspond to.`
                },
                { role: 'user', content: cleaned }
            ],
            stream: false
        });

        const json = await res.json();
        let assessmentResult = '';
        if (json.choices && json.choices[0] && json.choices[0].message) {
            assessmentResult = json.choices[0].message.content || '';
        } else if (json.output && json.output[0] && json.output[0].content && json.output[0].content[0]) {
            assessmentResult = json.output[0].content[0].text || '';
        }
        assessmentResult = assessmentResult.trim();

        let scaleLevel = NaN;
        const digitMatch = assessmentResult.match(/\b([1-5])\b/);
        if (digitMatch) {
            scaleLevel = parseInt(digitMatch[1], 10);
        } else {
            const lower = assessmentResult.toLowerCase();
            if (lower.includes('full ai')) scaleLevel = 5;
            else if (lower.includes('ai + human') || lower.includes('ai and human')) scaleLevel = 4;
            else if (lower.includes('editing')) scaleLevel = 3;
            else if (lower.includes('ideas') || lower.includes('structure')) scaleLevel = 2;
            else if (lower.includes('no ai')) scaleLevel = 1;
        }

        if (isNaN(scaleLevel)) {
            return [1];
        }
        return [scaleLevel];
    } catch (e) {
        console.error('Error assessing scale level:', e);
        return [1];
    }
}

export async function generateAlternativePrompt(userMessage) {
    try {
        const supportivePrompt = `As a supportive chatbot, suggest an alternative prompt based on the user's input that avoid meeting one of the following criteria: AI + Human Evaluation (AI generates content and humans refine/approve) or Full AI Responsibility (AI fully responsible with minimal human input). Create a maximum 50-word response prompt example aligned with either:\n• Ideas and Structure: AI generates ideas or structure while humans create the content, or\n• Research: AI is used as a research tool to find credible resources on a topic.\nWord this as a direct request (not a question). For example: 'Please generate ideas for an essay about (insert topic here)'.`;

        const cleanedUser = sanitizeContent(userMessage, 4000);
        const res = await callAzureOpenAI({
            messages: [
                { role: 'system', content: supportivePrompt },
                { role: 'user', content: cleanedUser }
            ],
            stream: false
        });

        const json = await res.json();
        let result = '';
        if (json.choices && json.choices[0] && json.choices[0].message) {
            result = json.choices[0].message.content || '';
        } else if (json.output && json.output[0] && json.output[0].content && json.output[0].content[0]) {
            result = json.output[0].content[0].text || '';
        }
        return result.trim();
    } catch (error) {
        console.error('Error generating alternative prompt:', error);
        return '';
    }
}
